### PR TITLE
move ts-essentials

### PR DESCRIPTION
**Pull request by amityadav0**

### CODE REVIEW

**Comment by amityadav0** [comment]
moved `ts-essentials` to devDependencies

`type-is` is not part of dependencies

**Comment by robert-zaremba** [comment]
Where do we use `ts-essentials` ?

**Comment by amityadav0** [comment]
we are using two functions from ts-essentials `DeepReadOnly` and `StrictOmit`

**Comment by amityadav0** [comment]
https://github.com/scale-it/algorand-builder/blob/e8d43ff72fcd744a4bc90b06da6557a497dad404/packages/algob/src/types.ts#L110

https://github.com/scale-it/algorand-builder/blob/e8d43ff72fcd744a4bc90b06da6557a497dad404/packages/algob/src/types.ts#L87

**Comment by amityadav0** [comment]
we can remove this dependency as instead of `DeepReadOnly` we can use `ReadOnly` because we don't need recursive one  for current use case

and same is for `StrictOmit` - we can use `Omit` for current use case

as the only difference is that `StrictOmit` checks strict filters , but for current code `Omit` is enough

**Comment by amityadav0** [comment]
but if in future if used some more complex types , then this will be useful

**Comment by robert-zaremba** [comment]
If you are sure that it's safe to remove it then we can do it. I'm approving the PR.

**Review by robert-zaremba — APPROVED** [review]

**Comment by amityadav0** [comment]
OK, removing

**Pull request merged**
